spacing         = 1
padding         = 0
hide_ascii      = true
separator       = " "
key_color       = "blue"
separator_color = "Yellow"

[palette]
type            = "Dark"
glyph           = "●  "
visible         = true

[randomize]
key_color       = true
separator_color = false
pool            = "base"

[keys]
distro          = "Distro"
kernel          = "Kernel"
de              = "DE"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
memory          = "Memory"
disk_space      = "Disk Space"
uptime          = "Uptime"