general.import = [
"~/projects/catppuccin/alacritty/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 80, lines = 20 }
padding = { x = 8, y = 8 }
decorations = "none"
opacity = 0.95

[font]
size = 18.0
normal = { family = "JetBrainsMono Nerd Font" }

